version: '3.8'
services:
  popin-app:
    build: .
    ports:
      - "80:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    env_file:
      - .env
    volumes:
      - uploads:/app/uploads

volumes:
  uploads: