services:
  popin-app:
    build: .
    ports:
      - "80:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    env_file:
      - .env
    volumes:
      - uploads:/app/uploads
    logging:
      driver: awslogs
      options:
        awslogs-group: /aws/docker/popin-app
        awslogs-region: ap-northeast-2
        awslogs-stream: popin
        awslogs-create-group: "true"

volumes:
  uploads: